// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------- //
// blink_input //
// ----------- //

#define blink_input_wrap_target 0
#define blink_input_wrap 10
#define blink_input_pio_version 0

static const uint16_t blink_input_program_instructions[] = {
            //     .wrap_target
    0x20a0, //  0: wait   1 pin, 0
    0x8080, //  1: pull   noblock
    0x6020, //  2: out    x, 32
    0xa041, //  3: mov    y, x
    0xe001, //  4: set    pins, 1
    0xbf42, //  5: nop                           [31]
    0x0085, //  6: jmp    y--, 5
    0xe000, //  7: set    pins, 0
    0xe05f, //  8: set    y, 31
    0xbf42, //  9: nop                           [31]
    0x0089, // 10: jmp    y--, 9
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program blink_input_program = {
    .instructions = blink_input_program_instructions,
    .length = 11,
    .origin = -1,
    .pio_version = blink_input_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config blink_input_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + blink_input_wrap_target, offset + blink_input_wrap);
    return c;
}
#endif

