# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oldMessage.proto
# Protobuf Python Version: 6.33.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    4,
    '',
    'oldMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10oldMessage.proto\"0\n\x0foperationStatus\x12\r\n\x05\x65stop\x18\x01 \x01(\x08\x12\x0e\n\x06manual\x18\x02 \x01(\x08\"g\n\x0fpositionCommand\x12\x0c\n\x04roll\x18\x03 \x01(\x11\x12\r\n\x05pitch\x18\x04 \x01(\x11\x12\x0b\n\x03yaw\x18\x05 \x01(\x11\x12\r\n\x05surge\x18\x06 \x01(\x11\x12\x0c\n\x04sway\x18\x07 \x01(\x11\x12\r\n\x05heave\x18\x08 \x01(\x11\"(\n\tMyMessage\x12\n\n\x02id\x18\t \x01(\x05\x12\x0f\n\x07\x63ontent\x18\n \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oldMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPERATIONSTATUS']._serialized_start=20
  _globals['_OPERATIONSTATUS']._serialized_end=68
  _globals['_POSITIONCOMMAND']._serialized_start=70
  _globals['_POSITIONCOMMAND']._serialized_end=173
  _globals['_MYMESSAGE']._serialized_start=175
  _globals['_MYMESSAGE']._serialized_end=215
# @@protoc_insertion_point(module_scope)
