import serial
from cobs import cobs
import message_pb2 # Generated by: protoc --python_out=. message.proto

# Identify your Pico's COM port (Check Device Manager)
ser = serial.Serial('COM7', 115200) 

raw_buffer = bytearray()

print("Waiting for data...")

while True:
    char = ser.read(1)
    if char == b'\x00': # End of COBS frame
        if raw_buffer:
            try:
                # 1. Unstuff COBS
                decoded = cobs.decode(raw_buffer)
                
                # 2. Parse Protobuf
                msg = message_pb2.MyMessage()
                msg.ParseFromString(decoded)
                
                print(f"Recv [ID: {msg.id}] Content: {msg.content}")
            except Exception as e:
                print(f"Decode Error: {e}")
            
            raw_buffer = bytearray()
    else:
        raw_buffer.extend(char)