/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "oldMessage.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(operationStatus, operationStatus, AUTO)


PB_BIND(positionCommand, positionCommand, AUTO)


PB_BIND(MyMessage, MyMessage, AUTO)



